export const GET_FRIENDS_LIST = "GET_FRIENDS_LIST";
export const SET_FRIENDS = "SET_FRIENDS";
export const LOADING_FRIENDS_LIST = "LOADING_FRIENDS_LIST";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
