export const GET_FRIENDS_LIST = "GET_FRIENDS_LIST";
export const SET_FRIENDS = "SET_FRIENDS";
export const LOADING_FRIENDS_LIST = "LOADING_FRIENDS_LIST";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
export const ADD_NEW_FRIEND = "ADD_NEW_FRIEND";
export const DELETE_FRIEND = "DELETE_FRIEND";
